"""Generate Localization/UiStrings.resx and UiStrings.de.resx for MacroRecorder.App."""
from __future__ import annotations

import pathlib
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[1] / "MacroRecorder.App" / "Localization"

EN: dict[str, str] = {
    "Common_AppTitle": "Macro Recorder by Rezondes",
    "Common_Ok": "OK",
    "Common_Yes": "Yes",
    "Common_No": "No",
    "Common_Cancel": "Cancel",
    "Main_WindowTitle": "Macro Recorder by Rezondes",
    "Shell_Back": "Back",
    "Shell_PinTopmost_ToolTip": "Keep this window on top of other windows",
    "Shell_PinTopmost_A11y": "Keep window on top",
    "Main_NewRecording": "Record new macro",
    "Main_Play": "Play",
    "Main_Export": "Export",
    "Main_Export_ToolTip": "Export macro as JSON file (for sharing or debugging)",
    "Main_Export_FileFilter": "JSON (*.json)|*.json|All files (*.*)|*.*",
    "Main_Export_Success": "Macro exported to:\n{0}",
    "Main_Export_ErrorNotFound": "Macro could not be loaded for export.",
    "Main_Export_ErrorWrite": "Export failed: {0}",
    "Main_Edit": "Edit",
    "Main_Delete": "Delete",
    "Main_MacroListActionsFormat": "{0} actions · {1} · {2:dd.MM.yyyy HH:mm}",
    "Main_Play_ErrorNoMacro": "Macro not found or has no events.",
    "Main_Play_InterruptedByUser": "Playback was stopped because you used the keyboard or mouse.",
    "Main_PlaybackInterruptedModalTitle": "Playback stopped",
    "Main_Play_ErrorDetail": "Playback: {0}",
    "Main_DeleteConfirm": "Really delete macro \"{0}\"?",
    "Main_NewMacroDefaultName": "New macro",
    "Record_WindowTitle": "Recording",
    "Record_Description": "Recording captures keyboard, mouse, and window focus changes. Start → perform actions → Stop → enter a name.",
    "Record_Start": "Start recording",
    "Record_Stop": "Stop recording",
    "Record_StatusRunning": "Recording…",
    "Record_SaveTitle": "Save macro",
    "Record_SaveMessage": "Name for the macro:",
    "Record_DefaultMacroName": "New macro",
    "Record_Saved": "Macro saved.",
    "Record_OpenInEditor": "Open macro in editor?",
    "Editor_DefaultWindowTitle": "Edit macro",
    "Editor_WindowTitleFormat": "Edit: {0}",
    "Editor_LabelMacro": "Macro",
    "Editor_RecordingStart": "Start recording",
    "Editor_RecordingStop": "Stop recording",
    "Editor_Save": "Save",
    "Editor_Undo": "Undo",
    "Editor_Redo": "Redo",
    "Editor_PlayTest": "Play test",
    "Editor_ShareJson": "Share JSON",
    "Editor_ShareJson_ToolTip": "View or export the current macro as JSON",
    "Editor_ShareJson_ModalTitle": "Macro JSON",
    "Editor_ShareJson_Close": "Close",
    "Editor_ShareJson_Export": "Export…",
    "Editor_Rename": "Rename…",
    "Editor_SectionSelection": "SELECTION",
    "Editor_MoveUp": "Move up ↑ (Alt+↑)",
    "Editor_MoveDown": "Move down ↓ (Alt+↓)",
    "Editor_Duplicate": "Duplicate (Ctrl+D)",
    "Editor_EditRow": "Edit row…",
    "Editor_Delete": "Delete (Del)",
    "Editor_SectionInsert": "INSERT",
    "Editor_SectionRecording": "RECORDING",
    "Editor_RecordMouseMoves": "Record mouse movements",
    "Editor_UseFocusBoundMousePositions": "Use focus-bound position",
    "Editor_UseFocusBoundMousePositions_ToolTip": "Mouse positions are global screen coordinates until a window receives focus (focus-change row). After that they are client coordinates relative to the foreground window until focus is lost or another window is focused. Each focus row stores that window's client size when available; playback resolves windows by title and process name and checks size when recorded.",
    "Playback_FocusTarget_AnchorMissing": "Playback cannot start: this macro uses focus-bound mouse positions, but no anchor window was stored. Turn the option off or re-record with a valid foreground window.",
    "Playback_FocusTarget_WindowNotFound": "Playback cannot start: the window \"{0}\" (process {1}) from the recording was not found.",
    "Playback_FocusTarget_ClientSizeMismatch": "Playback cannot start: the client area size no longer matches the recording. Expected {0}×{1} pixels, current window is {2}×{3} pixels.",
    "Editor_MenuInsertStep": "Insert step…",
    "Editor_MenuWaitBefore": "Delay · before selection",
    "Editor_MenuWaitAfter": "Delay · after selection",
    "Editor_MenuMouseBefore": "Mouse click · before selection",
    "Editor_MenuMouseAfter": "Mouse click · after selection",
    "Editor_MenuKeyBefore": "Key press · before selection",
    "Editor_MenuKeyAfter": "Key press · after selection",
    "Editor_HintInsertDrag": "Insert refers to the selected row · double-click edits a single row · drag rows to reorder (top/bottom half = before/after).",
    "Editor_GridAction": "Action",
    "Editor_GridValue": "Value",
    "Editor_ConfirmCloseWhileRecording": "Recording is active. Close without applying the new events?",
    "Editor_FirstSaveTitle": "Save macro",
    "Editor_FirstSaveMessage": "Name for the macro:",
    "Editor_UnsavedChangesTitle": "Unsaved changes",
    "Editor_UnsavedChangesMessage": "Changes to \"{0}\" have not been saved. What would you like to do?",
    "Editor_UnsavedDiscard": "Discard",
    "Editor_MacroNotFound": "Macro not found.",
    "Editor_StatusRecordingFormat": "Recording · {0} actions in overview · {1} captured events · playback total approx. {2}",
    "Editor_StatusNoEvents": "No events.",
    "Editor_StatusSavedFormat": "{0} actions in overview · {1} saved events · playback total approx. {2}",
    "Editor_PromptWaitTitle": "Delay",
    "Editor_PromptWaitMessage": "Wait time in milliseconds (digits only, at least 1):",
    "Editor_PromptWaitDefault": "500",
    "Editor_PromptWaitErrorRequired": "Please enter a value.",
    "Editor_PromptWaitErrorNumber": "Only digits are allowed.",
    "Editor_PromptWaitErrorMin": "Enter at least 1 millisecond.",
    "Editor_PromptWaitSpinUp": "Increase by 1",
    "Editor_PromptWaitSpinDown": "Decrease by 1",
    "Editor_RecordingStartErrorFormat": "Could not start recording: {0}",
    "Editor_RecordingStopError": "An error occurred while stopping recording.",
    "Editor_PlayTestInterrupted": "The test run was stopped because you used the keyboard or mouse.",
    "Editor_PlayTest_ErrorFormat": "Test: {0}",
    "Editor_EditMousePathNotSupported": "Mouse move groups cannot be edited here individually (only delete, move, or duplicate).",
    "Editor_Saved": "Saved.",
    "Editor_Event_MousePath": "Mouse movement",
    "Editor_MousePathValueFormat": "{0} steps, {1} ms, ({2}, {3}) → ({4}, {5})",
    "DialogInsertMouse_Title": "Insert mouse click",
    "DialogInsertMouse_Heading": "Mouse click",
    "DialogInsertMouse_Description": "Choose the mouse button and enter screen coordinates (X/Y in pixels). Use “Insert step” in the editor to place the step on the timeline.",
    "DialogInsertMouse_LabelX": "X (pixels)",
    "DialogInsertMouse_LabelY": "Y (pixels)",
    "DialogInsertKey_Title": "Insert key press",
    "DialogRename_Title": "Rename macro",
    "DialogEditEvent_Title": "Edit event",
    "DialogEdit_EventNotEditable": "This event type cannot be edited here.",
    "DialogKeyStroke_ModifierHint": "Note: insert modifiers separately – key detected: {0}",
    "DialogKeyStroke_StatusExtended": ", extended",
    "DialogKeyStroke_StatusFormat": "VK {0}, Scan {1}{2}",
    "DialogKeyStroke_EnterKeyFirst": "Press a key first.",
    "DialogRename_EnterName": "Please enter a name.",
    "DialogEdit_Field_KeyCurrent": "Current key",
    "DialogEdit_RescanKey": "Capture key from keyboard",
    "DialogEdit_Field_Extended": "Extended key",
    "DialogEdit_Field_AltDown": "Alt key held",
    "DialogEdit_Field_X": "X",
    "DialogEdit_Field_Y": "Y",
    "DialogEdit_Field_Button": "Button (Left/Right/Middle/X1/X2)",
    "DialogEdit_Field_Delta": "Delta",
    "DialogEdit_Field_Horizontal": "Horizontal wheel",
    "DialogEdit_Field_WaitMs": "Wait time (ms)",
    "DialogEdit_Field_DelayBeforeMs": "Delay before this step (ms)",
    "DialogEdit_Field_WindowTitle": "Window title",
    "DialogEdit_Field_ProcessName": "Process name",
    "DialogEdit_Field_Hwnd": "HWND (optional)",
    "DialogEdit_Field_Pid": "PID (optional)",
    "DialogEdit_Field_ReferenceClientWidth": "Reference client width (px, optional)",
    "DialogEdit_Field_ReferenceClientHeight": "Reference client height (px, optional)",
    "Event_Action_KeyDown": "Key (down)",
    "Event_Action_KeyUp": "Key (up)",
    "Event_Action_MouseMove": "Mouse (position)",
    "Event_Action_MouseWheel": "Mouse wheel",
    "Event_Action_FocusChanged": "Focus change",
    "Event_Action_FocusLost": "Focus cleared (global mouse)",
    "Event_Action_SyntheticWait": "Wait",
    "Event_Action_MouseButtonDownFormat": "Mouse ({0} down)",
    "Event_Action_MouseButtonUpFormat": "Mouse ({0} up)",
    "Event_MouseButton_Left": "left",
    "Event_MouseButton_Right": "right",
    "Event_MouseButton_Middle": "middle",
    "Event_MouseButton_X1": "X1",
    "Event_MouseButton_X2": "X2",
    "Main_Menu_Language": "Language",
    "Main_Menu_LanguageGerman": "Deutsch",
    "Main_Menu_LanguageEnglish": "English",
    "Main_Settings_Title": "Settings",
    "Main_Settings_GearToolTip": "Settings",
    "Main_Settings_PageTitle": "Settings",
    "Main_Settings_TabGeneral": "General",
    "Main_Settings_TabVisuals": "Visuals",
    "Main_Settings_TabMacro": "Macro",
    "Settings_Macro_MouseMoveMinLabel": "Minimum pixel distance between recorded mouse moves",
    "Settings_Macro_PlaybackGraceLabel": "Start delay after clicking \"Play\" (0 = off)",
    "Settings_Macro_PlaybackFocusHeader": "When focus changes during playback",
    "Settings_Macro_PlaybackFocusBringToForeground": "Bring target window to the foreground",
    "Settings_Macro_PlaybackFocusRestoreIfMinimized": "Restore if minimized",
    "Settings_PlaybackFocusUnsavedPairFormat": "{0} / {1}",
    "Settings_UnsavedCategoryMacro": "Mouse move recording",
    "Settings_UnsavedCategoryPlaybackGrace": "Playback start delay (ms)",
    "Settings_UnsavedCategoryPlaybackFocus": "Playback: focus target window",
    "Visuals_AppearanceModeHeader": "Appearance",
    "Visuals_Light": "Light",
    "Visuals_Dark": "Dark",
    "Visuals_ColorThemeHeader": "Color theme",
    "Visuals_ApplyTheme": "Use theme",
    "Appearance_UnsavedTitle": "Unsaved appearance",
    "Appearance_UnsavedMessage": "Your theme or light/dark mode has not been saved. What would you like to do?",
    "Visuals_UnsavedSave": "Save appearance",
    "Visuals_UnsavedDiscard": "Discard preview",
    "Theme_Name_BlueGrey": "Blue grey",
    "Theme_Name_Indigo": "Indigo",
    "Theme_Name_Teal": "Teal",
    "Theme_Name_DeepPurple": "Deep purple",
    "Theme_Name_Amber": "Amber",
    "Main_Settings_LanguageHeader": "Language",
    "Main_Settings_Save": "Save",
    "Settings_UnsavedTitle": "Unsaved settings",
    "Settings_UnsavedIntro": "The following changes have not been saved:",
    "Settings_UnsavedOutro": "What would you like to do?",
    "Settings_UnsavedChangeFormat": "{0}: {1} → {2}",
    "Settings_UnsavedCategoryLanguage": "Language",
    "Settings_UnsavedCategoryAppearanceMode": "Appearance mode",
    "Settings_UnsavedSave": "Save changes",
    "Settings_UnsavedDiscard": "Discard changes",
    "Main_Play_ErrorPlaybackFailed": "Playback could not be started.",
    "DialogInsertKey_Heading": "Key press",
    "DialogInsertKey_Description": "Click in this window and press a key. Prefer inserting modifiers (Ctrl, Alt, …) as separate steps.",
    "DialogInsertKey_PressKeyHint": "Press a key…",
    "DialogRename_LabelName": "Name",
    "DialogEdit_HeadingValues": "Adjust values",
    "DialogEdit_DescriptionValues": "Only this event is changed; timings are recalculated afterward.",
    "Editor_Value_KeyUpFormat": "VK {0}, Scan {1}",
    "Editor_Value_MouseMoveFormat": "{0}, {1} @ {2}",
    "Editor_Value_MouseWheelFormat": "{0}, {1} · Δ {2}{3}",
    "Editor_Value_MouseWheelHorizontalSuffix": " (horizontal)",
    "Editor_Value_FocusFormat": "{0}, {1}{2}",
    "Editor_Value_FocusLost": "Global mouse coordinates",
    "Editor_Value_FocusHwndFormat": " (HWND {0})",
    "Playback_Overlay_WarningTitle": "Macro is playing",
    "Playback_Overlay_WarningBody": "Do not use the keyboard or mouse, or playback will stop.",
    "Playback_Overlay_StartDelayFormat": "Starts in {0}",
    "Playback_Overlay_RemainingFormat": "About {0} remaining (estimated)",
    "Playback_Overlay_CancelPlayback": "Cancel playback",
    "Main_QueueCreator_ToolTip": "Macro queue creator…",
    "QueueCreator_WindowTitle": "Macro queue",
    "QueueCreator_QueueNameLabel": "Queue name",
    "QueueCreator_LoopWholeQueue": "Loop entire queue until stopped",
    "QueueCreator_EstimatedDurationFormat": "Estimated duration (one pass): {0}",
    "QueueCreator_AvailableMacros": "Available macros",
    "QueueCreator_Steps": "Queue steps",
    "QueueCreator_AddStep": "Add step",
    "QueueCreator_Remove": "Remove",
    "QueueCreator_Duplicate": "Duplicate",
    "QueueCreator_MoveUp": "Move up",
    "QueueCreator_MoveDown": "Move down",
    "QueueCreator_Save": "Save…",
    "QueueCreator_Load": "Load…",
    "QueueCreator_Run": "Run queue",
    "QueueCreator_Stop": "Stop",
    "QueueCreator_Pause": "Pause",
    "QueueCreator_Resume": "Resume",
    "QueueCreator_RepeatShort": "×",
    "QueueCreator_InitialDelayShort": "Initial delay (h:m:s)",
    "QueueCreator_BetweenRunsShort": "Between repeats (h:m:s)",
    "QueueCreator_PostStepShort": "After step (h:m:s)",
    "QueueCreator_TimeHint": "Time span, e.g. 0:2:10 for 2 minutes 10 seconds (hours:minutes:seconds).",
    "QueueCreator_TimelineHeader": "Preview timeline (one pass)",
    "QueueCreator_TimelineLine": "{0} — {1} (run {2}/{3})",
    "QueueCreator_FileFilter": "Queue JSON (*.json)|*.json|All files (*.*)|*.*",
    "QueueCreator_ErrorInvalidTime": "Enter each delay as hours:minutes:seconds (for example 0:0:30).",
    "QueueCreator_ErrorInvalidRepeat": "Repeat count must be a whole number of at least 1.",
    "QueueCreator_ErrorNoSteps": "Add at least one queue step.",
    "QueueCreator_ErrorSave": "Could not save queue: {0}",
    "QueueCreator_ErrorLoad": "Could not load queue: {0}",
    "QueueCreator_ErrorMissingMacro": "Macro not found: {0}",
    "QueueCreator_ErrorEmptyMacro": "Macro has no events: {0}",
    "QueueCreator_ConfirmMissingMacros": "Some steps reference macros that are not in your library. Run the queue anyway?",
    "QueueCreator_ConfirmLeaveWhileRunning": "A queue run is in progress. Stop the run and leave this page?",
}

DE: dict[str, str] = {
    "Common_AppTitle": "Macro Recorder by Rezondes",
    "Common_Ok": "OK",
    "Common_Yes": "Ja",
    "Common_No": "Nein",
    "Common_Cancel": "Abbrechen",
    "Main_WindowTitle": "Macro Recorder by Rezondes",
    "Shell_Back": "Zurück",
    "Shell_PinTopmost_ToolTip": "Dieses Fenster über allen anderen Fenstern anheften",
    "Shell_PinTopmost_A11y": "Fenster immer im Vordergrund",
    "Main_NewRecording": "Neues Makro aufzeichnen",
    "Main_Play": "Abspielen",
    "Main_Export": "Exportieren",
    "Main_Export_ToolTip": "Makro als JSON-Datei exportieren (zum Teilen oder zur Fehlersuche)",
    "Main_Export_FileFilter": "JSON (*.json)|*.json|Alle Dateien (*.*)|*.*",
    "Main_Export_Success": "Makro exportiert nach:\n{0}",
    "Main_Export_ErrorNotFound": "Makro konnte für den Export nicht geladen werden.",
    "Main_Export_ErrorWrite": "Export fehlgeschlagen: {0}",
    "Main_Edit": "Editieren",
    "Main_Delete": "Löschen",
    "Main_MacroListActionsFormat": "{0} Aktionen · {1} · {2:dd.MM.yyyy HH:mm}",
    "Main_Play_ErrorNoMacro": "Makro nicht gefunden oder keine Ereignisse.",
    "Main_Play_InterruptedByUser": "Die Makro-Wiedergabe wurde durch Ihre Eingabe (Tastatur oder Maus) beendet.",
    "Main_PlaybackInterruptedModalTitle": "Wiedergabe beendet",
    "Main_Play_ErrorDetail": "Wiedergabe: {0}",
    "Main_DeleteConfirm": "Makro „{0}“ wirklich löschen?",
    "Main_NewMacroDefaultName": "Neues Makro",
    "Record_WindowTitle": "Aufnahme",
    "Record_Description": "Aufnahme erfasst Tastatur, Maus und Fensterwechsel. Start → Aktionen ausführen → Stop → Namen vergeben.",
    "Record_Start": "Aufnahme starten",
    "Record_Stop": "Aufnahme stoppen",
    "Record_StatusRunning": "Aufnahme läuft…",
    "Record_SaveTitle": "Makro speichern",
    "Record_SaveMessage": "Name für das Makro:",
    "Record_DefaultMacroName": "Neues Makro",
    "Record_Saved": "Makro gespeichert.",
    "Record_OpenInEditor": "Makro im Editor öffnen?",
    "Editor_DefaultWindowTitle": "Makro bearbeiten",
    "Editor_WindowTitleFormat": "Bearbeiten: {0}",
    "Editor_LabelMacro": "Makro",
    "Editor_RecordingStart": "Aufnahme starten",
    "Editor_RecordingStop": "Aufnahme stoppen",
    "Editor_Save": "Speichern",
    "Editor_Undo": "Rückgängig",
    "Editor_Redo": "Wiederholen",
    "Editor_PlayTest": "Test abspielen",
    "Editor_ShareJson": "JSON teilen",
    "Editor_ShareJson_ToolTip": "Aktuelles Makro als JSON anzeigen oder exportieren",
    "Editor_ShareJson_ModalTitle": "Makro-JSON",
    "Editor_ShareJson_Close": "Schließen",
    "Editor_ShareJson_Export": "Exportieren…",
    "Editor_Rename": "Umbenennen…",
    "Editor_SectionSelection": "AUSWAHL",
    "Editor_MoveUp": "Nach oben ↑ (Alt+↑)",
    "Editor_MoveDown": "Nach unten ↓ (Alt+↓)",
    "Editor_Duplicate": "Duplizieren (Strg+D)",
    "Editor_EditRow": "Zeile bearbeiten…",
    "Editor_Delete": "Löschen (Entf)",
    "Editor_SectionInsert": "EINFÜGEN",
    "Editor_SectionRecording": "AUFNAHME",
    "Editor_RecordMouseMoves": "Mausbewegungen aufnehmen",
    "Editor_UseFocusBoundMousePositions": "Fokusgebundene Position nutzen",
    "Editor_UseFocusBoundMousePositions_ToolTip": "Mauspositionen sind globale Bildschirmkoordinaten, bis ein Fenster den Fokus erhält (Fokuswechsel-Zeile). Danach sind sie Client-Koordinaten relativ zum Vordergrundfenster, bis der Fokus verloren geht oder ein anderes Fenster fokussiert wird. Jede Fokus-Zeile speichert bei Bedarf die Client-Größe; beim Abspielen wird jedes Fenster anhand Titel und Prozessname aufgelöst und die Größe geprüft (wenn mitgespeichert).",
    "Playback_FocusTarget_AnchorMissing": "Wiedergabe nicht möglich: Dieses Makro nutzt fokusgebundene Mauspositionen, aber es wurde kein Anker-Fenster gespeichert. Option deaktivieren oder mit gültigem Vordergrundfenster neu aufnehmen.",
    "Playback_FocusTarget_WindowNotFound": "Wiedergabe nicht möglich: Das Fenster \"{0}\" (Prozess {1}) aus der Aufnahme wurde nicht gefunden.",
    "Playback_FocusTarget_ClientSizeMismatch": "Wiedergabe nicht möglich: Die Client-Größe passt nicht mehr zur Aufnahme. Erwartet {0}×{1} Pixel, aktuelles Fenster {2}×{3} Pixel.",
    "Editor_MenuInsertStep": "Schritt einfügen…",
    "Editor_MenuWaitBefore": "Wartezeit · vor der Auswahl",
    "Editor_MenuWaitAfter": "Wartezeit · nach der Auswahl",
    "Editor_MenuMouseBefore": "Mausklick · vor der Auswahl",
    "Editor_MenuMouseAfter": "Mausklick · nach der Auswahl",
    "Editor_MenuKeyBefore": "Tastendruck · vor der Auswahl",
    "Editor_MenuKeyAfter": "Tastendruck · nach der Auswahl",
    "Editor_HintInsertDrag": "Einfügen bezieht sich auf die markierte Zeile · Doppelklick bearbeitet eine Einzelzeile · Zeilen per Drag-and-Drop verschieben (obere/untere Hälfte = Position davor/danach).",
    "Editor_GridAction": "Aktion",
    "Editor_GridValue": "Wert",
    "Editor_ConfirmCloseWhileRecording": "Aufnahme läuft. Ohne Übernehmen der neuen Ereignisse schließen?",
    "Editor_FirstSaveTitle": "Makro speichern",
    "Editor_FirstSaveMessage": "Name für das Makro:",
    "Editor_UnsavedChangesTitle": "Ungespeicherte Änderungen",
    "Editor_UnsavedChangesMessage": "Änderungen an „{0}“ wurden nicht gespeichert. Wie möchten Sie fortfahren?",
    "Editor_UnsavedDiscard": "Verwerfen",
    "Editor_MacroNotFound": "Makro nicht gefunden.",
    "Editor_StatusRecordingFormat": "Aufnahme läuft · {0} Aktionen in der Übersicht · {1} erfasste Ereignisse · Wiedergabe Gesamtdauer ca. {2}",
    "Editor_StatusNoEvents": "Keine Ereignisse.",
    "Editor_StatusSavedFormat": "{0} Aktionen in der Übersicht · {1} gespeicherte Ereignisse · Wiedergabe Gesamtdauer ca. {2}",
    "Editor_PromptWaitTitle": "Verzögerung",
    "Editor_PromptWaitMessage": "Wartezeit in Millisekunden (nur Ziffern, mindestens 1):",
    "Editor_PromptWaitDefault": "500",
    "Editor_PromptWaitErrorRequired": "Bitte einen Wert eingeben.",
    "Editor_PromptWaitErrorNumber": "Nur Ziffern sind erlaubt.",
    "Editor_PromptWaitErrorMin": "Mindestens 1 Millisekunde eingeben.",
    "Editor_PromptWaitSpinUp": "Um 1 erhöhen",
    "Editor_PromptWaitSpinDown": "Um 1 verringern",
    "Editor_RecordingStartErrorFormat": "Aufnahme konnte nicht gestartet werden: {0}",
    "Editor_RecordingStopError": "Beim Beenden der Aufnahme ist ein Fehler aufgetreten.",
    "Editor_PlayTestInterrupted": "Der Testlauf wurde durch Ihre Eingabe (Tastatur oder Maus) beendet.",
    "Editor_PlayTest_ErrorFormat": "Test: {0}",
    "Editor_EditMousePathNotSupported": "Mausbewegungs-Gruppen können hier nicht einzeln bearbeitet werden (nur löschen, verschieben oder duplizieren).",
    "Editor_Saved": "Gespeichert.",
    "Editor_Event_MousePath": "Mausbewegung",
    "Editor_MousePathValueFormat": "{0} Schritte, {1} ms, ({2}, {3}) → ({4}, {5})",
    "DialogInsertMouse_Title": "Mausklick einfügen",
    "DialogInsertMouse_Heading": "Mausklick",
    "DialogInsertMouse_Description": "Maustaste wählen und Bildschirmkoordinaten (X/Y in Pixel) eingeben. Die Schrittposition in der Timeline legen Sie im Editor über „Schritt einfügen“ fest.",
    "DialogInsertMouse_LabelX": "X (Pixel)",
    "DialogInsertMouse_LabelY": "Y (Pixel)",
    "DialogInsertKey_Title": "Tastendruck einfügen",
    "DialogRename_Title": "Makro umbenennen",
    "DialogEditEvent_Title": "Ereignis bearbeiten",
    "DialogEdit_EventNotEditable": "Dieser Ereignistyp kann hier nicht bearbeitet werden.",
    "DialogKeyStroke_ModifierHint": "Hinweis: Modifier einzeln einfügen – Taste erkannt: {0}",
    "DialogKeyStroke_StatusExtended": ", erweitert",
    "DialogKeyStroke_StatusFormat": "VK {0}, Scan {1}{2}",
    "DialogKeyStroke_EnterKeyFirst": "Bitte zuerst eine Taste drücken.",
    "DialogRename_EnterName": "Bitte einen Namen eingeben.",
    "DialogEdit_Field_KeyCurrent": "Aktuelle Taste",
    "DialogEdit_RescanKey": "Taste von Tastatur übernehmen",
    "DialogEdit_Field_Extended": "Erweitert (Extended)",
    "DialogEdit_Field_AltDown": "Alt-Taste gehalten",
    "DialogEdit_Field_X": "X",
    "DialogEdit_Field_Y": "Y",
    "DialogEdit_Field_Button": "Button (Left/Right/Middle/X1/X2)",
    "DialogEdit_Field_Delta": "Delta",
    "DialogEdit_Field_Horizontal": "Horizontales Scrollen",
    "DialogEdit_Field_WaitMs": "Wartezeit (ms)",
    "DialogEdit_Field_DelayBeforeMs": "Verzögerung vor diesem Schritt (ms)",
    "DialogEdit_Field_WindowTitle": "Fenstertitel",
    "DialogEdit_Field_ProcessName": "Prozessname",
    "DialogEdit_Field_Hwnd": "HWND (optional)",
    "DialogEdit_Field_Pid": "PID (optional)",
    "DialogEdit_Field_ReferenceClientWidth": "Referenz-Clientbreite (px, optional)",
    "DialogEdit_Field_ReferenceClientHeight": "Referenz-Clienthöhe (px, optional)",
    "Event_Action_KeyDown": "Taste (unten)",
    "Event_Action_KeyUp": "Taste (hoch)",
    "Event_Action_MouseMove": "Maus (Position)",
    "Event_Action_MouseWheel": "Mausrad",
    "Event_Action_FocusChanged": "Fokuswechsel",
    "Event_Action_FocusLost": "Fokus verloren (globale Maus)",
    "Event_Action_SyntheticWait": "Warten",
    "Event_Action_MouseButtonDownFormat": "Maus ({0} unten)",
    "Event_Action_MouseButtonUpFormat": "Maus ({0} hoch)",
    "Event_MouseButton_Left": "links",
    "Event_MouseButton_Right": "rechts",
    "Event_MouseButton_Middle": "Mitte",
    "Event_MouseButton_X1": "X1",
    "Event_MouseButton_X2": "X2",
    "Main_Menu_Language": "Sprache",
    "Main_Menu_LanguageGerman": "Deutsch",
    "Main_Menu_LanguageEnglish": "English",
    "Main_Settings_Title": "Einstellungen",
    "Main_Settings_GearToolTip": "Einstellungen",
    "Main_Settings_PageTitle": "Einstellungen",
    "Main_Settings_TabGeneral": "Allgemein",
    "Main_Settings_TabVisuals": "Darstellung",
    "Main_Settings_TabMacro": "Makro",
    "Settings_Macro_MouseMoveMinLabel": "Mindeständerungen für Mausbewegungsaufzeichnung",
    "Settings_Macro_PlaybackGraceLabel": "Startverzögerung nach Klick auf „Abspielen“ (0 = aus)",
    "Settings_Macro_PlaybackFocusHeader": "Bei Fokuswechsel während der Wiedergabe",
    "Settings_Macro_PlaybackFocusBringToForeground": "Zielfenster in den Vordergrund holen",
    "Settings_Macro_PlaybackFocusRestoreIfMinimized": "Entminimieren, wenn minimiert",
    "Settings_PlaybackFocusUnsavedPairFormat": "{0} / {1}",
    "Settings_UnsavedCategoryMacro": "Mausbewegungsaufzeichnung",
    "Settings_UnsavedCategoryPlaybackGrace": "Wiedergabe: Startverzögerung (ms)",
    "Settings_UnsavedCategoryPlaybackFocus": "Wiedergabe: Fokus-Zielfenster",
    "Visuals_AppearanceModeHeader": "Erscheinungsbild",
    "Visuals_Light": "Hell",
    "Visuals_Dark": "Dunkel",
    "Visuals_ColorThemeHeader": "Farbschema",
    "Visuals_ApplyTheme": "Schema übernehmen",
    "Appearance_UnsavedTitle": "Ungespeicherte Darstellung",
    "Appearance_UnsavedMessage": "Farbschema oder Hell-/Dunkelmodus wurde nicht gespeichert. Wie möchten Sie fortfahren?",
    "Visuals_UnsavedSave": "Darstellung speichern",
    "Visuals_UnsavedDiscard": "Vorschau verwerfen",
    "Theme_Name_BlueGrey": "Blaugrau",
    "Theme_Name_Indigo": "Indigo",
    "Theme_Name_Teal": "Türkis",
    "Theme_Name_DeepPurple": "Tiefviolett",
    "Theme_Name_Amber": "Bernstein",
    "Main_Settings_LanguageHeader": "Sprache",
    "Main_Settings_Save": "Speichern",
    "Settings_UnsavedTitle": "Ungespeicherte Einstellungen",
    "Settings_UnsavedIntro": "Folgende Änderungen wurden noch nicht gespeichert:",
    "Settings_UnsavedOutro": "Wie möchten Sie fortfahren?",
    "Settings_UnsavedChangeFormat": "{0}: {1} → {2}",
    "Settings_UnsavedCategoryLanguage": "Sprache",
    "Settings_UnsavedCategoryAppearanceMode": "Erscheinungsbild",
    "Settings_UnsavedSave": "Änderungen speichern",
    "Settings_UnsavedDiscard": "Änderungen verwerfen",
    "Main_Play_ErrorPlaybackFailed": "Wiedergabe konnte nicht gestartet werden.",
    "DialogInsertKey_Heading": "Tastendruck",
    "DialogInsertKey_Description": "Klicken Sie ins Fenster und drücken Sie eine Taste. Modifier (Strg, Alt, …) am besten als eigene Schritte einfügen.",
    "DialogInsertKey_PressKeyHint": "Taste drücken …",
    "DialogRename_LabelName": "Name",
    "DialogEdit_HeadingValues": "Werte anpassen",
    "DialogEdit_DescriptionValues": "Nur dieses Ereignis wird geändert; die Zeiten werden danach automatisch neu berechnet.",
    "Editor_Value_KeyUpFormat": "VK {0}, Scan {1}",
    "Editor_Value_MouseMoveFormat": "{0}, {1} @ {2}",
    "Editor_Value_MouseWheelFormat": "{0}, {1} · Δ {2}{3}",
    "Editor_Value_MouseWheelHorizontalSuffix": " (horizontal)",
    "Editor_Value_FocusFormat": "{0}, {1}{2}",
    "Editor_Value_FocusLost": "Globale Mauskoordinaten",
    "Editor_Value_FocusHwndFormat": " (HWND {0})",
    "Playback_Overlay_WarningTitle": "Makro läuft",
    "Playback_Overlay_WarningBody": "Keine Eingaben mit Tastatur oder Maus, sonst bricht die Wiedergabe ab.",
    "Playback_Overlay_StartDelayFormat": "Start in {0}",
    "Playback_Overlay_RemainingFormat": "Noch ca. {0}",
    "Playback_Overlay_CancelPlayback": "Abspielen abbrechen",
    "Main_QueueCreator_ToolTip": "Makro-Warteschlange…",
    "QueueCreator_WindowTitle": "Makro-Warteschlange",
    "QueueCreator_QueueNameLabel": "Name der Warteschlange",
    "QueueCreator_LoopWholeQueue": "Gesamte Warteschlange wiederholen, bis Stopp",
    "QueueCreator_EstimatedDurationFormat": "Geschätzte Dauer (ein Durchlauf): {0}",
    "QueueCreator_AvailableMacros": "Verfügbare Makros",
    "QueueCreator_Steps": "Schritte",
    "QueueCreator_AddStep": "Schritt hinzufügen",
    "QueueCreator_Remove": "Entfernen",
    "QueueCreator_Duplicate": "Duplizieren",
    "QueueCreator_MoveUp": "Nach oben",
    "QueueCreator_MoveDown": "Nach unten",
    "QueueCreator_Save": "Speichern…",
    "QueueCreator_Load": "Laden…",
    "QueueCreator_Run": "Warteschlange ausführen",
    "QueueCreator_Stop": "Stopp",
    "QueueCreator_Pause": "Pause",
    "QueueCreator_Resume": "Weiter",
    "QueueCreator_RepeatShort": "×",
    "QueueCreator_InitialDelayShort": "Startverzögerung (h:m:s)",
    "QueueCreator_BetweenRunsShort": "Zwischen Wiederholungen (h:m:s)",
    "QueueCreator_PostStepShort": "Nach Schritt (h:m:s)",
    "QueueCreator_TimeHint": "Zeitspanne, z. B. 0:2:10 für 2 Minuten 10 Sekunden (Stunden:Minuten:Sekunden).",
    "QueueCreator_TimelineHeader": "Vorschau-Zeitleiste (ein Durchlauf)",
    "QueueCreator_TimelineLine": "{0} — {1} (Lauf {2}/{3})",
    "QueueCreator_FileFilter": "Warteschlange JSON (*.json)|*.json|Alle Dateien (*.*)|*.*",
    "QueueCreator_ErrorInvalidTime": "Bitte jede Pause als Stunden:Minuten:Sekunden eingeben (z. B. 0:0:30).",
    "QueueCreator_ErrorInvalidRepeat": "Wiederholungen müssen eine ganze Zahl ≥ 1 sein.",
    "QueueCreator_ErrorNoSteps": "Fügen Sie mindestens einen Schritt hinzu.",
    "QueueCreator_ErrorSave": "Warteschlange konnte nicht gespeichert werden: {0}",
    "QueueCreator_ErrorLoad": "Warteschlange konnte nicht geladen werden: {0}",
    "QueueCreator_ErrorMissingMacro": "Makro nicht gefunden: {0}",
    "QueueCreator_ErrorEmptyMacro": "Makro ohne Ereignisse: {0}",
    "QueueCreator_ConfirmMissingMacros": "Einige Schritte verweisen auf Makros, die in der Bibliothek fehlen. Trotzdem ausführen?",
    "QueueCreator_ConfirmLeaveWhileRunning": "Die Warteschlange läuft noch. Ausführung beenden und die Seite verlassen?",
}


def build_resx(strings: dict[str, str]) -> str:
    root = ET.Element("root")
    headers = [
        ("resmimetype", "text/microsoft-resx"),
        ("version", "2.0"),
        (
            "reader",
            "System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
        ),
        (
            "writer",
            "System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
        ),
    ]
    for name, val in headers:
        h = ET.SubElement(root, "resheader", {"name": name})
        ET.SubElement(h, "value").text = val
    for key in sorted(strings.keys()):
        data = ET.SubElement(root, "data", {"name": key, "{http://www.w3.org/XML/1998/namespace}space": "preserve"})
        ET.SubElement(data, "value").text = strings[key]
    return '<?xml version="1.0" encoding="utf-8"?>\n' + ET.tostring(root, encoding="unicode")


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    (ROOT / "UiStrings.resx").write_text(build_resx(EN), encoding="utf-8")
    (ROOT / "UiStrings.de.resx").write_text(build_resx(DE), encoding="utf-8")
    print("Wrote", ROOT / "UiStrings.resx")
    print("Wrote", ROOT / "UiStrings.de.resx")


if __name__ == "__main__":
    main()
